---
abstract: 'provide the needed bits to be a XML-RPC client'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-XMLRPC-Client
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::Cookies: 0
  MooseX::Role::Parameterized: 0.02
  MooseX::Types: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  RPC::XML::Client: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://hg.fedoraproject.org//hg/camelus
version: 0.02
